### ISSUE TITLE
various errors

### ISSUE THREAD

**Issue by ManiaccoUniBZ** [ibaiGorordo/IWR1443-Read-Data-Python#17]
Hi!
first, thank you so much for the code. It is exactly what I am looking for.

I am using an AWR1443Boost module (same as IWR1443 but it handles better high temperatures).
I need to run the code (I have Microsoft Visual Studio Code v1.73.1). but seem always to run in some errors (I am quite new to python).

Which version of the various packages (numpy, pyqtgraph, ecc...) do  I need to make it run smoothly?
I saw you posted this code 4 years ago but when I installed the versions of that time I still get the same errors.

First I got
`Traceback (most recent call last):
  File "c:\Users\ViconPC\Desktop\IWR1443-Read-Data-Python-MMWAVE-SDK-1-master\readData_IWR1443.py", line 304, in <module>
    app = QtGui.QApplication([])
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'. Did you mean: 'QGuiApplication'?`

which I fixed by changing the code at the beginning (I left your code as a comment)
`import serial
import time
import numpy as np
import pyqtgraph as pg
#from pyqtgraph.Qt import QtGui
import pyqtgraph.Qt.QtWidgets as QtGui`

It fixed that error but I still get the following:
`Traceback (most recent call last):
  File "c:\Users\ViconPC\Desktop\IWR1443-Read-Data-Python-MMWAVE-SDK-1-master\readData_IWR1443.py", line 308, in <module>
    win = pg.GraphicsWindow(title="2D scatter plot")
AttributeError: module 'pyqtgraph' has no attribute 'GraphicsWindow'. Did you mean: 'GraphicsView'? `

I tried everything and do seem to be able to handle it.

Can you help me?

Thank you

**Comment by Lilii13** [comment]
Hello, working with the same code for same purposes (only with an AWR6843AOPEVM board), if you got it working and got any experience with it, could you please help me to knwo what I should adapt/change for it to work with my board ? (Packages version, and others).
Thanks a lot.

**Comment by ManiaccoUniBZ** [comment]
Hi,
the board was useless in the end for our needs.
Therefore we did not continue.

We did encounter plenty of difficulties and the customer support was useless.

Sorry to be not helpful.

Greetings,

- - -
Maximilian Maniacco
Phd - Advanced Systems for Engineering
***@***.***
________________________________

**Comment by Ayano57** [comment]
hello working with this code for iwr1443 if any of you solved the issues u were facing if you could let me know the code changes and improvements it will be highly appreciated.
Thanks
